export const ERROR_CODES = {
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  DUPLICATE_RESOURCE: "DUPLICATE_RESOURCE",
  AUTHENTICATION_REQUIRED: "AUTHENTICATION_REQUIRED",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",
  AUTHORIZATION_DENIED: "AUTHORIZATION_DENIED",
  ACCOUNT_DEACTIVATED: "ACCOUNT_DEACTIVATED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  PROJECT_NOT_ACCEPTING: "PROJECT_NOT_ACCEPTING",
  INVESTMENT_ALREADY_WITHDRAWN: "INVESTMENT_ALREADY_WITHDRAWN",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
};

export const HTTP = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL: 500,
};

export const CACHE_KEYS = {
  PROJECTS_LIST: "projects:list",
  PROJECT_BY_ID: (id) => `projects:${id}`,
  PORTFOLIO: (userId) => `portfolio:${userId}`,
  ANALYTICS: "admin:analytics",
};

export const CACHE_TTL = {
  PROJECTS_LIST: 60,
  PROJECT_BY_ID: 120,
  PORTFOLIO: 30,
  ANALYTICS: 300,
};

export const RATE = {
  GLOBAL: { windowMs: 15 * 60 * 1000, max: 300 },
  AUTH: { windowMs: 15 * 60 * 1000, max: 20 },
  INVEST: { windowMs: 60 * 1000, max: 10 },
  ADMIN: { windowMs: 5 * 60 * 1000, max: 100 },
};

export const TOKEN_EXPIRY = "7d";
export const RESET_EXPIRY_MS = 15 * 60 * 1000;
export const MIN_INVESTMENT = 100;

export const AUDIT = {
  USER_REGISTERED: "USER_REGISTERED",
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  PROFILE_UPDATED: "PROFILE_UPDATED",
  PROJECT_CREATED: "PROJECT_CREATED",
  PROJECT_UPDATED: "PROJECT_UPDATED",
  PROJECT_DELETED: "PROJECT_DELETED",
  INVESTMENT_CREATED: "INVESTMENT_CREATED",
  INVESTMENT_WITHDRAWN: "INVESTMENT_WITHDRAWN",
};
